// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/uscms_data/d3/xinlongl/projects/XHY4bRun3/X_HY_4b_Run3_BDT/Auxilary/DecapitatedBDT_datasetPreparation/./simpleDiscretizer.cc";

#endif
