import numpy as np
import matplotlib.pyplot as plt
import mplhep as hep
import ROOT as r
plt.style.use(hep.style.CMS)
from PyHist import PyHist
import copy
import matplotlib
import os
import sys
import json
DIR_TOP = os.environ["ANA_TOP"]
sys.path.append(DIR_TOP)
with open(DIR_TOP + "raw_nano/color_scheme.json", "r") as f:
    color_scheme = json.load(f)
colours = {
    # CMS 10-colour-scheme from
    # https://cms-analysis.docs.cern.ch/guidelines/plotting/colors/#categorical-data-eg-1d-stackplots
    "darkblue": "#3f90da",
    "lightblue": "#92dadd",
    "orange": "#e76300",
    "red": "#bd1f01",
    "darkpurple": "#832db6",
    "brown": "#a96b59",
    "gray": "#717581",
    "beige": "#b9ac70",
    "yellow": "#ffa90e",
    "lightgray": "#94a4a2",
    # extra colours
    "darkred": "#A21315",
    "green": "#7CB518",
    "mantis": "#81C14B",
    "forestgreen": "#2E933C",
    "darkgreen": "#064635",
    "purple": "#9381FF",
    "deeppurple": "#36213E",
    "ashgrey": "#ACBFA4",
    "canary": "#FFE51F",
    "arylideyellow": "#E3C567",
    "earthyellow": "#D9AE61",
    "satinsheengold": "#C8963E",
    "flax": "#EDD382",
    "vanilla": "#F2F3AE",
    "dutchwhite": "#F5E5B8",
}
BG_COLOURS = {
    "QCD": "darkblue",
    "TT": "brown",
    "W+Jets": "orange",
    "Z+Jets": "yellow"
}
errorbar_style = {
    'linestyle': 'none',
    'marker': '.',      # display a dot for the datapoint
    'elinewidth': 2,    # width of the errorbar line
    'markersize': 15,   # size of the error marker
    #'capsize': 4,       # size of the caps on the errorbar (0: no cap fr)
    'color': 'k',       # black
}

# Data point styling parameters
DATA_STYLE = {
    "histtype": "errorbar",
    "color": "black",
    "markersize": 15,
    "elinewidth": 2,
    "capsize": 0,
}

stack_style = {
    'edgecolor': (0, 0, 0, 0.5),
}

# hatch_style = {
#     'facecolor': 'none',
#     'edgecolor': 'black',#'#9c9ca1',
#     'alpha': 1,
#     'linewidth': 0,
#     'hatch': '//'
# }

hatch_style = {
    'color':'black',
    'alpha':0.2
}

# Get the binning along the 2DAlphabet-defined X-axis (No need to modify this function)
def get_binning_x(hLow,hSig,hHigh):
    bins = []
    for i in range(1,hLow.GetNbinsX()+1):
        bins.append(hLow.GetXaxis().GetBinLowEdge(i))
    for i in range(1,hSig.GetNbinsX()+1):
        bins.append(hSig.GetXaxis().GetBinLowEdge(i))
    for i in range(1,hHigh.GetNbinsX()+2):#low edge of overflow is high edge of last bin
        bins.append(hHigh.GetXaxis().GetBinLowEdge(i))
    bins = np.array(bins,dtype='float64')
    return bins

# Get the binning along the 2DAlphabet-defined Y-axis (No need to modify this function)
def get_binning_y(hLow,hSig,hHigh):
    #histos should have same binning in Y
    bins = []
    for i in range(1,hLow.GetNbinsY()+2):
        bins.append(hLow.GetYaxis().GetBinLowEdge(i))
    bins = np.array(bins,dtype='float64')
    return bins

# Open the postfit shapes file generated by CombineHarvester's PostFit2DShapesFromWorkspace function
# No need to modify this function
def get2DPostfitPlot(_file, process, region, prefit=False):
    if not r.TFile.Open(_file):
        raise FileNotFoundError(f"The file '{file}' does not exist or cannot be opened.")

    f = r.TFile.Open(_file)
    fitStatus = "prefit" if prefit else "postfit"


    h2 = f.Get(f"{region}_{fitStatus}/{process}")
    print(_file, f"{region}_{fitStatus}/{process}")
    h2.SetDirectory(0)
    return h2


# Get all the 2D histograms from a given region, for all the processes (data, signal, bkg) in that region
# No need to modify this function
def get_hists(input_file,region,processes,prefit=False):
    histos_region_dict = {}
    for process in processes:
        h2 = get2DPostfitPlot(input_file,process,region,prefit)
        histos_region_dict[process]=h2
    return histos_region_dict


if __name__ == "__main__":

    from argparse import ArgumentParser
    parser = ArgumentParser()
    parser.add_argument('--prefit', dest='prefit',
                        action='store_true',
                        help='Plot prefit distributions instead of postfit')
    parser.add_argument('--sig', dest='sig', type=str,
                        action='store', default='MX-3000_MY-300',
                        help='mx-my signal mass to plot')
    parser.add_argument('--pass_name', dest='pass_name', type=str, action='store', default='SR1_Region0')
    parser.add_argument('--fail_name', dest='fail_name', type=str, action='store', default='SB1_Region0')
    parser.add_argument('--title_extra', dest='title_extra', type=str, action='store')
    parser.add_argument('--tf', dest='tf', type=str, action='store', default='tf')
    parser.add_argument('--do_sig', dest='do_sig', action='store_true')
    parser.add_argument('--method', dest='method', type=int, action='store', default=0)
    args = parser.parse_args()
    
    
    prefit = args.prefit
    mx = args.sig.split('-')[0][3:]
    my = args.sig.split('-')[1][3:]

    #######################################################################
    # Change this to point to your postfit shapes file (b-only, generally)
    #######################################################################
    input_file = f"postfitshapes_b.root"


    #######################################################################
    # Gather the names of all of the processes you'd find in the postfit
    # shapes file. In my case, they were separated by year so I have this.
    # You will probably have to change these names.
    #######################################################################  
    procs = ["Allyears__MC_TTBarJets",  f"Allyears__SignalMC_XHY4b_{args.sig}"]
    # Here, I'm just adding the QCD and observed data + total background histogram names.
    # You will need to change the QCD names based on how you named them in 2DA, 
    # but the `data_obs` and `TotalBkg` processes don't need to be changed - these are Combine default names
    if args.method == 0:
        base_pass_name=args.pass_name[:-8]
        base_fail_name=args.fail_name[:-8]
    else:
        base_pass_name=args.pass_name[1:-8]
        base_fail_name=args.fail_name[1:-8]
    print(base_pass_name, base_fail_name)
    procs_SR_pass = procs + [f'QCD_pass_{base_pass_name}_{args.tf}', 'data_obs', 'TotalBkg']
    procs_SR_fail = procs + [f'QCD_fail_{base_fail_name}',     'data_obs', 'TotalBkg']
    
    # Now I just make a region : {process : TH2} dictionary using the get_hists helper function.
    # Change the region names to suit what you're plotting.
    histos_dict = {}
    print(input_file, args.fail_name, procs_SR_fail)
    histos_dict[args.fail_name] = get_hists(input_file,args.fail_name,procs_SR_fail,prefit)
    histos_dict[args.pass_name] = get_hists(input_file,args.pass_name,procs_SR_pass,prefit)
    print(histos_dict)    
    # Create empty dictionaries for the latex names of each process and their color in the plot
    labels_dict = {}
    colors_dict = {}
    # Loop over all processes in the Fail and Pass regions
    for key in procs_SR_pass + procs_SR_fail:
        if key in labels_dict: continue
        if key in colors_dict: continue
        else:
            if 'TTBar' in key:
                label = r'$t\bar{t}$'
                color = color_scheme["MC_TTBarJets"]
            elif 'QCD' in key:
                label = 'Multijet'
                color = color_scheme["MC_QCDJets"]
            elif 'Signal' in key:
                label = f'Signal MX {mx} GeV, MY {my} GeV'
                color = "SignalMC_XHY4b"
            colors_dict[key] = color
            labels_dict[key] = label

    for region, processes in {
        args.pass_name:procs_SR_pass,    # region : [processes]
        args.fail_name:procs_SR_fail
    }.items():
        for axis in ['X','Y']:
            ################################################################################################
            # Change all these variables to suit your plot/analysis needs
            ################################################################################################
            axis_label = "$\mathit{m}_{X}^{rec}$ [TeV]" if axis == "X" else "$\mathit{m}_{Y}^{rec}$ [TeV]"
            file_suffix = "mX" if axis == "X" else "mY"
            x_range = [0,5] if axis == "X" else [0,4]

            # Don't change this - this is the TH2:ProjectionX/Y method used to get the 1D projections
            projection_method = f"Projection{axis}"

            # Extract histograms - don't change this code.
            histos = histos_dict[region]

            # Get the data histogram
            h_data = getattr(histos["data_obs"], projection_method)(f"data_{axis}")     # Get the 1D projection of the data onto this axis
            h_data.SetBinErrorOption(1)                                                 # Poisson error
            h_data = PyHist(h_data)                                                     # Convert TH1 ---> numpy array via PyHist helper

            # Now get all of the MC histograms. No need to change this code
            h_mc = []
            labels_mc = []
            colors_mc = []
            for process in processes:
                h_temp = getattr(histos[process], projection_method)(f"{process}_{axis}")
                h_temp = PyHist(h_temp)
                h_name = h_temp.histo_name
                h_mc.append(h_temp)
                labels_mc.append(labels_dict[process])
                colors_mc.append(colors_dict[process])

            # Get the total background estimate histogram. No need to change this code
            h_bkg = getattr(histos["TotalBkg"], projection_method)(f"bkg_{axis}")
            h_bkg = PyHist(h_bkg)

            #######################################################################################
            # Now we have to concatenate all of the histograms
            #######################################################################################
            
            # No need to change this code
            edges = h_data.bin_edges
            centersData = h_data.get_bin_centers()

            # K:V {label:color}
            label_colors = dict(zip(labels_mc, colors_mc))

            #############################################################################################
            # Concatenate processes per year. You will have to modify this code based on your processes.
            # Basically, we are just booking empty numpy histograms to fill with all of the year-by-year 
            # histograms of each of the processes.
            #############################################################################################
            tt  = np.zeros_like(h_data.bin_values)
            xy  = np.zeros_like(h_data.bin_values)
            qcd = np.zeros_like(h_data.bin_values)
            # Now concatenate all the 1D histograms (now stored as numpy arrays). Change the processes here to fit your needs
            for h in h_mc:
                hname = h.histo_name
                if 'TTBar' in hname:
                    tt += h.bin_values
                elif 'Signal' in hname:
                    xy += h.bin_values
                elif 'QCD' in hname:
                    qcd += h.bin_values
                else:
                    continue

            # Set up plotting
            plt.style.use([hep.style.CMS])
            fig, (ax, rax) = plt.subplots(
                2, 1, figsize=(12, 14), gridspec_kw={"height_ratios": [3, 1], "hspace": 0.1}, sharex=True
            )

            # Concatenate V+jets bkg into "other"  ----> This was specific to my analysis. Yours will probably be different
            #other = wj + zj
            # Organize backgrounds in opposite order of yields (lowest first). You'll have to find this order for your own analysis
            bkg_yields = np.array([ tt, qcd])
            bkg_colors = [colors_dict["Allyears__MC_TTBarJets"],colors_dict[f"QCD_fail_{base_fail_name}"]]
            bkg_labels = [r'$t\bar{t}$','QCD']

            # Organize signal -----------------> modify to fit your needs
            sig_yields = xy
            sig_colors = '#bd1f01'
            sig_scale  = 10.671 # postfit signal strength for S+B. You can get this from the MultiDimFit output for S+B
            sig_labels = r'$X[%s]\to HY[%s]$'%(mx, my)

            # Organize data -----------------> no need to modify this code
            yerr = h_data.get_error_pairs() 
            xerrorsData = [width / 2 for width in h_data.bin_widths]

            # Organize uncertainty on the bkg prediction ---------> no need to modify this code
            tot_err = h_bkg.get_error_pairs()
            y1 = bkg_yields.sum(axis=0) - tot_err[0]
            y2 = bkg_yields.sum(axis=0) + tot_err[1]

            # Plot backgrounds --------> no need to modify this code
            hep.histplot(bkg_yields, edges, ax=ax, stack=True, label=bkg_labels, histtype="fill",facecolor=bkg_colors)

            # Plot signal in Pass
            if args.fail_name not in region and args.do_sig: # modify this logic if your region names are different 
                ax.step(x=edges, y=np.hstack([sig_yields,sig_yields[-1]])*sig_scale, where='post', label=sig_labels, color=sig_colors, linewidth=3)

            # Plot data -----------> no need to modify this code
            ax.errorbar(x=centersData, y=h_data.bin_values, xerr=xerrorsData, yerr=yerr, label='Data', capsize=0, **errorbar_style)

            # Plot systematic uncertainty -----------> no need to modify this code
            ax.fill_between(x=edges, y1=np.hstack([y1,y1[-1]]), y2=np.hstack([y2,y2[-1]]), step='post', label=r'Total bkg. unc.', **hatch_style, linewidth=0.0)

            # Calculate pulls. Here, simply data-bkg / sqrt(stat**2 + syst**2). Change to whatever you want
            sigma    = np.sqrt(h_data.bin_error**2 + h_bkg.bin_error**2)
            slabel   = r"$\sigma$"
            rax_ylim = 3.5  # Pull plot y-axis limit
            pulls = (h_data.bin_values - h_bkg.bin_values) / (sigma + 1e-3)

            # Plot pulls in rax
            hep.histplot(pulls, edges, yerr=np.ones_like(pulls), xerr=True, ax=rax, **DATA_STYLE, label=r"(Data - Bkg.) / " + slabel)

            # Plot the bkg uncertainty normalized by sigma as a band in the pull plot axis if you want. this is just an example of how to do it
            '''
            eUp = np.zeros_like(pulls) + hTotalBkg.bin_error / (sigma + 1e-3)
            eDn = np.zeros_like(pulls) - hTotalBkg.bin_error / (sigma + 1e-3)
            rax.fill_between(
                x=edges,
                y1=np.hstack([eUp, eUp[-1]]),
                y2=np.hstack([eDn, eDn[-1]]),
                step='post',
                label=r"$\sigma_\mathrm{syst}$ / $\sigma_\mathrm{stat}$",
                **hatch_style,
                linewidth=0
            )
            '''

            # Plot the signal contribution in the pull plot
            if args.fail_name not in region and args.do_sig:
                # Plot signal in rax
                sig_rax = copy.deepcopy(sig_yields) * sig_scale
                sig_rax = sig_rax / (sigma + 1e-3)
                hep.histplot(sig_rax, edges, ax=rax, label=r'$X[%s]\to HY[%s]$ / $\sigma$'%(mx,my), histtype="step", color=sig_colors, linewidth=4)


            # Format Axes ------------------> modify to suit your needs
            yMaximum = max(h_data.bin_values)*1.5
            ax.set_ylim([0., yMaximum*1.2])
            ax.margins(x=0)
            ax.set_xlim([edges[0],edges[-1]])
            rax.set_ylim([-rax_ylim,rax_ylim])
            rax.margins(x=0)
            rax.hlines(0, *rax.get_xlim(), color=colours["gray"], linewidth=1)
            rax.set_xlim([edges[0],edges[-1]])
            ax.tick_params(axis="both", which="major", labelsize=36 - 4)

            # mplhep library commands. See here: https://mplhep.readthedocs.io/en/latest/
            lumiText = args.title_extra + r" ,Prelimilary, 173.2 $fb^{-1}$ (13.6 TeV)"
            hep.cms.lumitext(lumiText,ax=ax, fontsize=36)
            hep.cms.label(
                loc=1,          # Top left, single line, in-panel
                ax=ax,          # put CMS label in main plot frame (ax)
                label='',       # This is what goes after CMS. E.g. "Preliminary", "WiP", etc 
                rlabel='',  
                data=True,      # If False, then the plot will show "CMS Simulation". Otherwise, just "CMS"
                fontsize=36
            ) 
            rax.set_xlabel(axis_label, fontsize=36)
            rax.tick_params(axis="both", which="major", labelsize=36 - 4)
            ax.set_ylabel('<Events / bin>', fontsize=36)      # <Events / GeV> since we normalize by bin width
            ax.legend()
            # Change to suit your needs
            outname = f'perbin_{args.title_extra}_{region}_{args.tf}_{axis}.png'
            plt.savefig(outname, bbox_inches='tight')
